### ISSUE TITLE
Feedback General Astrid 

### ISSUE THREAD

**Issue by ah-bas-und-aer** [GuidaGG/vielfaeltig#10]
- [x] For screens smaller than 1600 px width no bars at teh side (layout for wide screens)
- [ } Colors: check all colors #7869BE / #FF8C00
- Menu: 
- [x] implement the ne menu icon
- [ ] slidebar transparent orange, no shadow
- [ ] ! Add sticky note „vielfältige Jobs“
  - [ ] style sticky buttons
- [ ] Buttons: I thought to have the bottons with a smooth animation (vgl. https://thehost.is/), fist they are „pressed in“/concarve and when hovered or activated they became convex (this is only if there is time and in case we can test it together), also the contrast between the button color and shadows needs to be higher (lighter grey)
- Footer: 
- [x] can we add Hyperlinks to the logo files of teh partnerts? 
- [x] footer can be more compressed in hight and with the smaller typesize (small text next to the quote)
- [x] Text links styling: 
purple with underlining
- [x] contact bottons in theupper area should be closer to the adress text, subtext (in small font size closer to the button
   - *Created a "less-margin" class that can be applied to elements like paragraphs to overrule the default margin-bottom*   
- [ ] TItele: 
title text should be as thick as the text of the logo (is it easier to have the logo as an implemented text instead of using the svg?) #2  
- [ ] he title must be place on top of the white gradiant and should stick to the top until the next chapter apears #2 
- [x] Accordeon: 
styling is not completed, in general more compact, much less padding,
instead of the arrows, please use the "+", without botton background, the icon can also be smaller as the other icons, but can also turn, when openend
- [ ] Headline:
We need a styling for headline, bold and as big as the paragraph text (it doesn't seem to be H3)
- [ ] Styling for list with more than one text row
- [ ] align the second line with the start of the text of the first line.

**Comment by GuidaGG** [comment]
# Headline:
We need a styling for headline, bold and as big as the paragraph text (it doesn't seem to be H3)

I dont understand this. Do you define the styling?

On the homepage I needed to add a special styling for the first H1 (because we need to have one for SEO/acessibility purposes). SInce they can add all types of Headings in the backend I think you could define rules for them, even if they all should just look the same.

**Comment by GuidaGG** [comment]
#instead of the arrows, please use the "+", without botton background, the icon can also be smaller as the other icons, but can also turn, when openend

can you send us the arrow? we dont have a reference for this. Or did you sent it in the icons?

**Comment by GuidaGG** [comment]
# implement the ne menu icon
slidely transparent orange, no shadow

can you also send us this new menu icon?

**Comment by GuidaGG** [comment]
regarding the footer:
- at the momen there are 2 instagram buttons. Is this still relevant? Which links/social buttons are going to be there?

**Comment by GuidaGG** [comment]
contact bottons in theupper area should be closer to the adress text, subtext (in small font size closer to the button

not 100% sure but I think you mean the buttons should be closer to

**Comment by GuidaGG** [comment]
#-  slidely transparent orange, no shadow

- i thin ki cant make the orange transparent. and with shadow you mean no shadow at all or just no drop shadow on hover?

**Comment by GuidaGG** [comment]
# Styling for list with more than one text row

can you give an example?
