### ISSUE TITLE
Feedback Astrid mobile 

### ISSUE THREAD

**Issue by ah-bas-und-aer** [GuidaGG/vielfaeltig#11]
<img width="373" alt="Bildschirmfoto 2024-01-29 um 19 03 18" src="https://github.com/GuidaGG/vielfaeltig/assets/124358378/91770f4f-4a23-430c-b9c4-697ffe2a4c79">
<img width="376" alt="Bildschirmfoto 2024-01-29 um 19 03 07" src="https://github.com/GuidaGG/vielfaeltig/assets/124358378/fba86f40-d0ae-4917-b169-d0b4346277b1">) sometimes content/page is strangley cropped (see screenshots)
- Can we move the menu icon element a bit further down (e.g. at the hight of the arrow button when menu opened) to give more space to the title?
- the squares below the buttons are still visible
- more padding between the chapters
- if the space is not enough for the title in one line,

**Comment by GuidaGG** [comment]
![image](https://github.com/GuidaGG/vielfaeltig/assets/9657908/d8eede3d-f246-4fc6-af4c-3cb7a25f387d)
I think even if we change the menu positiosn and reduce widths this still will not work in mobile. with such long titles
SHould we just use the sticky-aligned headers on the homepage? 

and on the other pages the headlines just stay on the page aligned to the left?
