### ISSUE TITLE
Contact form Styling

### ISSUE THREAD

**Issue by ah-bas-und-aer** [GuidaGG/vielfaeltig#24]
- the form should be a bit more structured (I have to thing how we can do it)
- in the mail that confirms the sending of the mail the logo should appear, do you know how I can do that?
- the favicon is hidden

**Comment by GuidaGG** [comment]
- I think this might work, but now it is not sending emails, so I cant test. Did you test with them? are they getting the answers?
![image](https://github.com/GuidaGG/vielfaeltig/assets/9657908/a202ae7d-81cf-4435-9c5a-ec0e0ca3ebc1)
- favicon was not set up on the dev. Or did you mean something else?

**Comment by ah-bas-und-aer** [comment]
The favicon also did not work on the real page. 
I tested myself with the mails, and at the moment Ben is rechecking

**Comment by ah-bas-und-aer** [comment]
-  can the warning texts be in orange instead of red?
- can we make the checkboxes bigger (hight of the text fields
- the botton „Durchsuchen“ should be styled like our bottons. It can also be the Download-Icon but 180° turned.
- titles above the text fields in medium
- more spacing between the elementgroups
- if you choose one text field can teh outline become transparent orange instead of transparent blue?

**Comment by ah-bas-und-aer** [comment]
can you add a reCAPTCHA or Akismet to the contactforms? It says it is not secure to use only mail inputs. Or what do you think about it?

**Comment by GuidaGG** [comment]
I think there is a plugin directly for that there. We could install and try. The dev server is not working now, I dont know why .

**Comment by farzadgo** [comment]
> * text

I did all of the design requests, plus had an eye on spacings etc. I hope it will work good as well on iPhones, anyways I did the changes using chrome browser let's hope for the best.

**Comment by GuidaGG** [comment]
Cool. Pull request and I merge it tomorrow in the morning and put it in the dev.
