### ISSUE TITLE
General

### ISSUE THREAD

**Issue by ah-bas-und-aer** [GuidaGG/vielfaeltig#35]
- [x] can the bottons inside an accordeon get the backgroun/circle back (besides the "+")
- [x] the spacing between the accordeon and next category title looks smaller than to the illustration (reduce spacing to illu, expand to accordeon) refers to mobile and desktop
- [ ] hyphenation (add f.i. Plugin WP_Typography), we can help with the settings
  - todo on production 
- [x] if possible create headlines with direfferent padding below (one with space one without is enough)
- [ ] ~~if possible first line of bulletpoints, when there is a forced break, in orange~~
- [x] for the small text size less padding (and less line hight as well for both mobile and dektop)
   - this also affects small text in the start of the page

**Comment by ah-bas-und-aer** [comment]
From the meeting yesterday: About the orange text style, can we just use one of the headline styles for the wish? (maybe one in medium and one in regular, in the size of paragraph with no padding below? 
Still I told them that it might not be possible, and that would be also fine.

**Comment by GuidaGG** [comment]
but then they wont be with the style of the lines, I think.
I will create a class "orange" that can be applied to elements so that hte text is orange.
