### ISSUE TITLE
Desktop, styling

### ISSUE THREAD

**Issue by ah-bas-und-aer** [GuidaGG/vielfaeltig#37]
Client wish: 
- size of the quote should be back to the small size of the paragraph text (medium) (for mobile and dektop)
- the small text size should be a bit bigger (font-size: 7rem i tested)
- more spacing after accordeon
- looking on running text: reduce spacing between paragraph spacing a bit more (if that is possible)
main page: wp-blocker below the categroy title smaller (I can also change it, no?)
margin-bottom_1.5rem

**Comment by GuidaGG** [comment]
- [ ] size of the quote should be back to the small size of the paragraph text (medium) (for mobile and dektop)
- [ ]  the small text size should be a bit bigger (font-size: 7rem i tested)
- [ ] more spacing after accordeon
- [ ] ooking on running text: reduce spacing between paragraph spacing a bit more (if that is possible)
- [ } 9 main page: wp-blocker below the categroy title smaller (I can also change it, no?)
margin-bottom_1.5rem

**Comment by GuidaGG** [comment]
- main page: wp-blocker below the categroy title smaller (I can also change it, no?)
margin-bottom_1.5rem

- i dont understand. can you give a print?

**Comment by ah-bas-und-aer** [comment]
> * main page: wp-blocker below the categroy title smaller (I can also change it, no?)
>       margin-bottom_1.5rem
> 
>     * i dont understand. can you give a print?

<img width="1536" alt="Bildschirmfoto 2024-02-08 um 10 42 14" src="https://github.com/GuidaGG/vielfaeltig/assets/124358378/68a44226-403f-4933-93de-ea8964b5c7d7">

I think I can change that manually in the backend, no?
