### ISSUE TITLE
Sticky titles header area

### ISSUE THREAD

**Issue by ah-bas-und-aer** [GuidaGG/vielfaeltig#50]
a)
- Turn the sticky titles into non sticky titles
- Align them to the right of the content and check anker points
- Add a white background to the header with a vertical gradiant

b) last idea of me, if haven't should of this
- let the page content fade out on the level of the header while scrolling
- exclude the sticky titles to this functionality

**Comment by GuidaGG** [comment]
@ah-bas-und-aer , you are a genius.

can you check if this is what you wanted?
https://dev.vielfaeltig-bremen.de/

**Comment by ah-bas-und-aer** [comment]
@GuidaGG I was just about to write you! I was wondering: wait a sec, can i believe my eyes?! Haha

**Comment by GuidaGG** [comment]
can I then upload to the online version?

**Comment by ah-bas-und-aer** [comment]
@GuidaGG yeah, but can content become absolut white in the header area? And the area where it fades out can be smaller, if this makes sense to you.

**Comment by GuidaGG** [comment]
![image](https://github.com/GuidaGG/vielfaeltig/assets/9657908/3a4be72c-01fa-4ede-8aa4-a368ca844c91)
like this?

**Comment by ah-bas-und-aer** [comment]
yes, but start the gradiant a bit earlier?  maybe just under the menu button?

**Comment by GuidaGG** [comment]
done

**Comment by ah-bas-und-aer** [comment]
<img width="1497" alt="Bildschirmfoto 2024-06-07 um 17 20 13" src="https://github.com/GuidaGG/vielfaeltig/assets/124358378/ed60463a-4cca-43e7-98b5-bc1ca5f66896">
as bespoken

**Comment by ah-bas-und-aer** [comment]
<img width="1493" alt="Bildschirmfoto 2024-06-07 um 17 21 Kopie" src="https://github.com/GuidaGG/vielfaeltig/assets/124358378/2b3dd2db-4d80-484f-9671-5c48281bc15e">
This should visualize how I mean to edit the area

**Comment by GuidaGG** [comment]
should be fixed
