### ISSUE TITLE
Further Additions

### ISSUE THREAD

**Issue by ah-bas-und-aer** [GuidaGG/vielfaeltig#55]
On the page we changed the order of content, (check staging page.)
- Add new text size: The orange text should be 20 % smaller than the headline 1, also the row spacing. This size should also go for the quote (section „Wir“)
- The ankor of "angebote“ is placed wrong then, (you have to explain to me how I do it correct, I did not get it)

**Comment by GuidaGG** [comment]
Dear Astrid,

I set up a new size for the H3 tag, which is the same now for the quote.
You have then to change the subtitle to H3 and please check if this afects other parts where the H3 tag might have been used, is so, these need to be hcanged to H4.

The other part I have to wait till I have access to do.

**Comment by ah-bas-und-aer** [comment]
The h3 seems to be the same size than running text now. It should be inbetween the two different sizes. 
I can check if there are other h3 of course.
